// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card-metadata--image': string;
  'card-metadata--info': string;
  'card-metadata--link': string;
  'card-metadata--name': string;
  'card-metadata--rating': string;
  'card-metadata--status': string;
  'card-metadata--wrapper': string;
  'card-wrapper': string;
  'h1': string;
  'h2': string;
  'h3': string;
  'h4': string;
  'h5': string;
  'h6': string;
}
export const cssExports: CssExports;
export default cssExports;
